namespace DungeonOfTheFallen.Core.Models
{
    public enum TileType
    {
        Floor,
        AshFloor,
        SandFloor,
        CloudFloor,
        CursedFloor,
        Wall,
        Exit,
        Spawn,
        Trap,
        ThornTrap,
        CurseTrap,
        LavaTrap,
        SpikeTrap,
        DivineTrap,
        HealingRoom,
        HealingShrine,
        HealingAltar,
        HotSpring,
        HealingBubble,
        LightCircle,
        LockedDoor,
        Puzzle,
        KeyPedestal
    }
}
